import { test, expect } from '@playwright/test';

test('tabs and interactive Python preserve state, handle blocks, input, errors and history', async ({ page }) => {
  await page.goto('./');
  await expect(page.locator('#run')).toBeEnabled({ timeout: 90000 });
  await expect(page.locator('#code-panel')).toBeVisible();
  await expect(page.locator('#terminal-panel')).toBeHidden();
  await expect(page.locator('#hint')).toBeHidden();
  await page.locator('#terminal-tab').click();
  await expect(page.locator('#code-panel')).toBeHidden();
  await page.locator('#interpreter').check();
  const input = page.locator('#terminal-input');
  const output = page.locator('#output');
  const prompt = page.locator('#prompt');
  async function command(code, next = '>>>') {
    await input.fill(code);
    await input.press('Enter');
    await expect(page.locator('#run')).toBeEnabled();
    await expect(prompt).toHaveText(next);
  }
  await command('x = 40');
  await input.fill('x + 2');
  await page.locator('#code-tab').click();
  await page.locator('#terminal-tab').click();
  await expect(input).toBeFocused();
  await expect(input).toHaveValue('x + 2');
  await page.keyboard.press('Enter');
  await expect(output).toContainText('\n42\n');
  await expect(input).toBeFocused();
  await command('x + 2');
  await expect(output).toContainText('\n42\n');
  await command('for i in range(2):', '...');
  await command('    print(i)', '...');
  await command('');
  await expect(output).toContainText('\n0\n1\n');
  await command('1 / 0');
  await expect(output).toContainText('ZeroDivisionError');
  await command('if :');
  await expect(output).toContainText('SyntaxError');
  await input.fill('name = input("Name: ")');
  await input.press('Enter');
  await expect(prompt).toHaveText('›');
  await page.locator('#code-tab').click();
  await page.locator('#terminal-tab').click();
  await expect(input).toBeFocused();
  await input.fill('Bjørn');
  await input.press('Enter');
  await expect(prompt).toHaveText('>>>');
  await command('name');
  await expect(output).toContainText("'Bjørn'");
  await input.press('ArrowUp');
  await expect(input).toHaveValue('name');
  await command('for i in range(2):', '...');
  await input.press('Control+c');
  await expect(prompt).toHaveText('>>>');
  await command('x');
  await expect(output).toContainText('\n40\n');
  await page.locator('#code-tab').click();
  await page.locator('#editor').fill('print("script")');
  await page.locator('#run').click();
  await expect(output).toContainText('script');
  await expect(input).toBeVisible();
  await command('x');
  await command('exit()');
  await expect(page.locator('#interpreter')).not.toBeChecked();
  await expect(input).toBeHidden();
  await page.locator('#interpreter').check();
  await page.screenshot({ path: `test-results/interpreter-${test.info().project.name}.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
